sudo: required
language: node_js
node_js: '8'
git:
  depth: 1
cache:
  yarn: true
  directories:
  - node_modules
branches:
  only:
  - master
env:
  global:
    secure: evtK3IWosNexQyyYcPo78LZptm4hXH9gkzVFxVWDFuFy1sPIE1Z/3G3SKdBbGmvnJQs2ATIYfc3CUnCKUMJN4aNtJv8jFcc+p6QMN60Yve/6UsDFrTPrV8uQBVJEkP1NwOWqWnamO+WM0RW6t0kp0yHPx0U7w9ndFnVhbHgveFpDXJobharxefH2FoBDp6WDt/R3U8o17sHm23hE7rK7kNx4mytbmdWKl/EJ7H/KQsoPw/hf9KdyOFIxTzVwLjbxg0ySmYtY0BGqIUCAhqqvEdvgJd+w4Fn+ZEwmK3esNDbc47HGN/x9MlnX32DBDyzXGThi5Is8wezcFxmNOY8IAU0Y6CN6tu0T+5ZIBEwDQAKZCoLzEotRetqKZoh2WTADeiTlyR8GvAClP6ahPtoCRx3je/gAEbWwbV77yB4n5nGkfOn3Xu9JTz3Rukd/dJ4+pPo6RAHA5V/UXoDDqrwjw/GVMkwqs31E+8b/PJsVYF58h3UAR/W1g25xatb+1QF14zeq3U4e20v4/xBw5HTT24jX42aJ1lBK2f9EAiBde9Hwxl3RA5+cvIHi09Xc/2z8Rn8B4hf8ZymltP8tPpbjHZGz8V47TVnfpbUAvh7PHiOOOtYc6XX0LcbA73dhvalYzgZMaGSe+rfW8BEcDEQK1uU5YK4ar/JN2rGzfHABkoI=
install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
- export PATH=$HOME/.yarn/bin:$PATH ;
script:
- yarn
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/c42ddc125fe6bbfccb48
    on_success: change
    on_failure: always
    on_start: never
before_deploy:
- printf "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}\n" >> ~/.npmrc
deploy:
  provider: script
  script: yarn run publish:next
  skip_cleanup: true
  on:
    branch: master
